services:
  uplox:
    build:
      context: .
      dockerfile: apps/uplox/Dockerfile.dev
    image: uplox-dev:latest
    container_name: uplox-uplox
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run dev
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://cache:6379
      - DATABASE_URL=postgresql://postgres:password@db:5432/uplox
      - MINIO_ENDPOINT=storage
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=miniosuperadmin
      - MINIO_SECRET_KEY=miniosuperadmin
      - MINIO_BUCKET=uplox
      - MINIO_REGION=us-east-1
      - SCANNER_HOST=scanner
      - SCANNER_PORT=3310
    depends_on:
      - db
      - cache
      - storage
    networks:
      - uplox-network

  scanner:
    build:
      context: .
      dockerfile: apps/scanner/Dockerfile.dev
    image: scanner-dev:latest
    container_name: uplox-scanner
    ports:
      - "3310:3310"
    volumes:
      - ./infra/scanner/clamav:/var/lib/clamav
      - ./apps/scanner/sample/sample.txt:/var/lib/clamav/sample.txt
      - ./apps/scanner/config/clamav_conf.conf:/etc/clamav/clamd.conf
      - ./apps/scanner/config/clamd.ctl:/var/run/clamav/clamd.ctl
    command: |
      freshclam &&
      clamd -c /etc/clamav/clamd.conf &&
      clamdscan --config-file=/etc/clamav/clamd.conf /var/lib/clamav/sample.txt
    healthcheck:
      test: ["CMD-SHELL", "timeout 5s bash -c '</dev/tcp/localhost/3310' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - uplox-network

  cache:
    image: redis/redis-stack:7.2.0-v17
    container_name: uplox-cache
    ports:
      - "6379:6379"
    volumes:
      - ./infra/cache:/data
    networks:
      - uplox-network

  storage:
    image: minio/minio:latest
    container_name: uplox-storage
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./infra/storage:/data
    environment:
      - MINIO_ROOT_USER=miniosuperadmin
      - MINIO_ROOT_PASSWORD=miniosuperadmin
      - MINIO_BUCKET=uplox
      - MINIO_REGION=us-east-1
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD-SHELL", "timeout 5s bash -c '</dev/tcp/localhost/9000' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - uplox-network

  db:
    image: postgres:15-alpine
    container_name: uplox-db
    ports:
      - "5432:5432"
    volumes:
      - ./infra/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=uplox
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - uplox-network

networks:
  uplox-network:
    driver: bridge
