{
 "title": "Uplox Application Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Presign duration (ms) (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(uplox_presign_duration_milliseconds_bucket[5m])) by (le, route))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload Duration Histogram (ms) (p95)",
   "type": "timeseries",
   "description": "Duration of upload requests in milliseconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(uplox_upload_request_duration_milliseconds_bucket[5m])) by (le, route))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Errors by Status",
   "type": "timeseries",
   "description": "Total number of API errors (4xx, 5xx)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(uplox_api_errors_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Virus Detections Over Time",
   "type": "timeseries",
   "description": "Total number of virus files detected by AV",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (virus_type) (rate(uplox_av_detection_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uploads Per File Type",
   "type": "timeseries",
   "description": "Total number upload per file type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (file_type) (increase(uplox_upload_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload throughput (bytes)",
   "type": "timeseries",
   "description": "Thoughput by route",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(uplox_throughput_bytes_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health Check Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(uplox_health_check_latency_milliseconds_bucket[5m])) by (le, endpoint))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}